import { POCKET_ICON_TYPES } from "@/shared/enums/pocket/pocket-icons.enums";
import {
  RiBankCardLine,
  RiBikeLine,
  RiBookLine,
  RiCameraLine,
  RiCarLine,
  RiComputerLine,
  RiCupLine,
  RiEmotionHappyLine,
  RiFilmLine,
  RiFootballLine,
  RiFootprintLine,
  RiGamepadLine,
  RiGasStationLine,
  RiGiftLine,
  RiGlobeLine,
  RiGovernmentLine,
  RiGraduationCapLine,
  RiHeadphoneLine,
  RiHeartLine,
  RiHeartsFill,
  RiHome2Line,
  RiHospitalLine,
  RiLeafLine,
  RiMusicLine,
  RiPlaneLine,
  RiRepeatLine,
  RiRestaurantLine,
  RiRocketLine,
  RiSafeLine,
  RiSailboatLine,
  RiShoppingBagLine,
  RiSmartphoneLine,
  RiStarLine,
  RiStockLine,
  RiSuitcaseLine,
  RiToolsLine,
  RiUmbrellaLine,
  RiVipDiamondLine,
  RiWeightLine,
  RiWifiLine,
  RiWrenchLine,
} from "@remixicon/react";

export const POCKET_ICONS: Record<
  POCKET_ICON_TYPES,
  { label: string; icon: React.ReactNode }
> = {
  [POCKET_ICON_TYPES.PLANE]: { label: "Travel", icon: <RiPlaneLine /> },
  [POCKET_ICON_TYPES.SUITCASE]: { label: "Trip", icon: <RiSuitcaseLine /> },
  [POCKET_ICON_TYPES.WALLET]: { label: "Wallet", icon: <RiBankCardLine /> },
  [POCKET_ICON_TYPES.HOME]: { label: "Home", icon: <RiHome2Line /> },
  [POCKET_ICON_TYPES.CAR]: { label: "Car", icon: <RiCarLine /> },
  [POCKET_ICON_TYPES.HEALTH]: { label: "Health", icon: <RiHeartLine /> },
  [POCKET_ICON_TYPES.EDUCATION]: {
    label: "Education",
    icon: <RiGraduationCapLine />,
  },
  [POCKET_ICON_TYPES.SHOPPING]: {
    label: "Shopping",
    icon: <RiShoppingBagLine />,
  },
  [POCKET_ICON_TYPES.EMERGENCY]: {
    label: "Emergency",
    icon: <RiUmbrellaLine />,
  },
  [POCKET_ICON_TYPES.SAVINGS]: { label: "Savings", icon: <RiSafeLine /> },
  [POCKET_ICON_TYPES.GIFT]: { label: "Gift", icon: <RiGiftLine /> },
  [POCKET_ICON_TYPES.ENTERTAINMENT]: {
    label: "Entertainment",
    icon: <RiMusicLine />,
  },
  [POCKET_ICON_TYPES.GAMING]: { label: "Gaming", icon: <RiGamepadLine /> },
  [POCKET_ICON_TYPES.FOOD]: { label: "Food", icon: <RiRestaurantLine /> },
  [POCKET_ICON_TYPES.MEDICAL]: { label: "Medical", icon: <RiHospitalLine /> },
  [POCKET_ICON_TYPES.FUEL]: { label: "Fuel", icon: <RiGasStationLine /> },
  [POCKET_ICON_TYPES.MAINTENANCE]: {
    label: "Maintenance",
    icon: <RiToolsLine />,
  },
  [POCKET_ICON_TYPES.NATURE]: { label: "Nature", icon: <RiLeafLine /> },
  [POCKET_ICON_TYPES.GOALS]: { label: "Goals", icon: <RiRocketLine /> },
  [POCKET_ICON_TYPES.STAR]: { label: "Favourite", icon: <RiStarLine /> },
  [POCKET_ICON_TYPES.BABY]: { label: "Baby", icon: <RiEmotionHappyLine /> },
  [POCKET_ICON_TYPES.BICYCLE]: { label: "Bicycle", icon: <RiBikeLine /> },
  [POCKET_ICON_TYPES.BOOK]: { label: "Book", icon: <RiBookLine /> },
  [POCKET_ICON_TYPES.CAMERA]: { label: "Camera", icon: <RiCameraLine /> },
  [POCKET_ICON_TYPES.COFFEE]: { label: "Coffee", icon: <RiCupLine /> },
  [POCKET_ICON_TYPES.COMPUTER]: { label: "Computer", icon: <RiComputerLine /> },
  [POCKET_ICON_TYPES.DOG]: { label: "Pet", icon: <RiFootprintLine /> },
  [POCKET_ICON_TYPES.DUMBBELL]: { label: "Fitness", icon: <RiWeightLine /> },
  [POCKET_ICON_TYPES.FILM]: { label: "Film", icon: <RiFilmLine /> },
  [POCKET_ICON_TYPES.GLOBE]: { label: "Global", icon: <RiGlobeLine /> },
  [POCKET_ICON_TYPES.GOVERNMENT]: { label: "Tax", icon: <RiGovernmentLine /> },
  [POCKET_ICON_TYPES.INVESTMENT]: {
    label: "Investment",
    icon: <RiStockLine />,
  },
  [POCKET_ICON_TYPES.JEWELRY]: { label: "Jewelry", icon: <RiVipDiamondLine /> },
  [POCKET_ICON_TYPES.MUSIC]: { label: "Music", icon: <RiHeadphoneLine /> },
  [POCKET_ICON_TYPES.PHONE]: { label: "Phone", icon: <RiSmartphoneLine /> },
  [POCKET_ICON_TYPES.SPORT]: { label: "Sport", icon: <RiFootballLine /> },
  [POCKET_ICON_TYPES.SUBSCRIPTION]: {
    label: "Subscription",
    icon: <RiRepeatLine />,
  },
  [POCKET_ICON_TYPES.TOOLS]: { label: "Tools", icon: <RiWrenchLine /> },
  [POCKET_ICON_TYPES.WEDDING]: { label: "Wedding", icon: <RiHeartsFill /> },
  [POCKET_ICON_TYPES.WIFI]: { label: "Internet", icon: <RiWifiLine /> },
  [POCKET_ICON_TYPES.YACHT]: { label: "Yacht", icon: <RiSailboatLine /> },
};
